# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: cwsandbox-client
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cwsandbox._proto import discovery_pb2 as coreweave_dot_sandbox_dot_v1_dot_discovery__pb2


class DiscoveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAvailableRunners = channel.unary_unary(
                '/coreweave.sandbox.v1.DiscoveryService/ListAvailableRunners',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.ListAvailableRunnersRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.ListAvailableRunnersResponse.FromString,
                )
        self.GetAvailableRunner = channel.unary_unary(
                '/coreweave.sandbox.v1.DiscoveryService/GetAvailableRunner',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.GetAvailableRunnerRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.AvailableRunner.FromString,
                )


class DiscoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAvailableRunners(self, request, context):
        """ListAvailableRunners lists the runners visible to the caller's organization,
        optionally filtered. RunnerView defaults to BASIC when unspecified.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableRunner(self, request, context):
        """GetAvailableRunner returns a single runner by id. Returns NOT_FOUND (reason
        CWSANDBOX_RUNNER_NOT_FOUND) if the runner is unknown or not visible.
        RunnerView defaults to FULL when unspecified.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAvailableRunners': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableRunners,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.ListAvailableRunnersRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.ListAvailableRunnersResponse.SerializeToString,
            ),
            'GetAvailableRunner': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableRunner,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.GetAvailableRunnerRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.AvailableRunner.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coreweave.sandbox.v1.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAvailableRunners(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.DiscoveryService/ListAvailableRunners',
            coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.ListAvailableRunnersRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.ListAvailableRunnersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailableRunner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.DiscoveryService/GetAvailableRunner',
            coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.GetAvailableRunnerRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_discovery__pb2.AvailableRunner.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
