# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: cwsandbox-client
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cwsandbox._proto import discovery_pb2 as coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2


class DiscoveryServiceStub(object):
    """DiscoveryService provides read-only endpoints for discovering available
    towers and runways visible to the authenticated user's organization.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAvailableTowers = channel.unary_unary(
                '/coreweave.aviato.v1beta1.DiscoveryService/ListAvailableTowers',
                request_serializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListAvailableTowersRequest.SerializeToString,
                response_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListAvailableTowersResponse.FromString,
                _registered_method=True)
        self.GetAvailableTower = channel.unary_unary(
                '/coreweave.aviato.v1beta1.DiscoveryService/GetAvailableTower',
                request_serializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.GetAvailableTowerRequest.SerializeToString,
                response_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.AvailableTower.FromString,
                _registered_method=True)
        self.ListRunways = channel.unary_unary(
                '/coreweave.aviato.v1beta1.DiscoveryService/ListRunways',
                request_serializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListRunwaysRequest.SerializeToString,
                response_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListRunwaysResponse.FromString,
                _registered_method=True)
        self.GetRunway = channel.unary_unary(
                '/coreweave.aviato.v1beta1.DiscoveryService/GetRunway',
                request_serializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.GetRunwayRequest.SerializeToString,
                response_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.RunwaySummary.FromString,
                _registered_method=True)


class DiscoveryServiceServicer(object):
    """DiscoveryService provides read-only endpoints for discovering available
    towers and runways visible to the authenticated user's organization.
    """

    def ListAvailableTowers(self, request, context):
        """ListAvailableTowers returns towers visible to the caller's organization,
        optionally filtered by capabilities.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableTower(self, request, context):
        """GetAvailableTower returns a single tower by ID, if visible to the caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunways(self, request, context):
        """ListRunways returns an aggregated view of runways across visible towers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunway(self, request, context):
        """GetRunway returns a single runway by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAvailableTowers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableTowers,
                    request_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListAvailableTowersRequest.FromString,
                    response_serializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListAvailableTowersResponse.SerializeToString,
            ),
            'GetAvailableTower': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableTower,
                    request_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.GetAvailableTowerRequest.FromString,
                    response_serializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.AvailableTower.SerializeToString,
            ),
            'ListRunways': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunways,
                    request_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListRunwaysRequest.FromString,
                    response_serializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListRunwaysResponse.SerializeToString,
            ),
            'GetRunway': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunway,
                    request_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.GetRunwayRequest.FromString,
                    response_serializer=coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.RunwaySummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coreweave.aviato.v1beta1.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coreweave.aviato.v1beta1.DiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """DiscoveryService provides read-only endpoints for discovering available
    towers and runways visible to the authenticated user's organization.
    """

    @staticmethod
    def ListAvailableTowers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.aviato.v1beta1.DiscoveryService/ListAvailableTowers',
            coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListAvailableTowersRequest.SerializeToString,
            coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListAvailableTowersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableTower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.aviato.v1beta1.DiscoveryService/GetAvailableTower',
            coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.GetAvailableTowerRequest.SerializeToString,
            coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.AvailableTower.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunways(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.aviato.v1beta1.DiscoveryService/ListRunways',
            coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListRunwaysRequest.SerializeToString,
            coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.ListRunwaysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunway(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.aviato.v1beta1.DiscoveryService/GetRunway',
            coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.GetRunwayRequest.SerializeToString,
            coreweave_dot_aviato_dot_v1beta1_dot_discovery__pb2.RunwaySummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
