# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: cwsandbox-client
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cwsandbox._proto import gateway_pb2 as coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2


class GatewayServiceStub(object):
    """----------------------------------------------------------------------------------
    Service Definition
    ----------------------------------------------------------------------------------

    GatewayService provides sandbox management capabilities.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/Start',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StartSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StartSandboxResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/Stop',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StopSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StopSandboxResponse.FromString,
                _registered_method=True)
        self.CreateFileSystemSnapshot = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/CreateFileSystemSnapshot',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.CreateFileSystemSnapshotRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.CreateFileSystemSnapshotResponse.FromString,
                _registered_method=True)
        self.GetFileSystemSnapshot = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/GetFileSystemSnapshot',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetFileSystemSnapshotRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.FileSystemSnapshot.FromString,
                _registered_method=True)
        self.ListFileSystemSnapshots = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/ListFileSystemSnapshots',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListFileSystemSnapshotsRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListFileSystemSnapshotsResponse.FromString,
                _registered_method=True)
        self.DeleteFileSystemSnapshot = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/DeleteFileSystemSnapshot',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteFileSystemSnapshotRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteFileSystemSnapshotResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/Get',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetSandboxResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/List',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListSandboxesRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListSandboxesResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/Delete',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteSandboxResponse.FromString,
                _registered_method=True)
        self.Exec = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/Exec',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ExecSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ExecSandboxResponse.FromString,
                _registered_method=True)
        self.AddFile = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/AddFile',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.AddFileSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.AddFileSandboxResponse.FromString,
                _registered_method=True)
        self.RetrieveFile = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/RetrieveFile',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RetrieveFileSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RetrieveFileSandboxResponse.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/Pause',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.PauseSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.PauseSandboxResponse.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/Resume',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ResumeSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ResumeSandboxResponse.FromString,
                _registered_method=True)
        self.Raw = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/Raw',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RawSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RawSandboxResponse.FromString,
                _registered_method=True)
        self.GetObjectStorageWIFConfig = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/GetObjectStorageWIFConfig',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetObjectStorageWIFConfigRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ObjectStorageWIFConfig.FromString,
                _registered_method=True)
        self.SetObjectStorageWIFConfig = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/SetObjectStorageWIFConfig',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.SetObjectStorageWIFConfigRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ObjectStorageWIFConfig.FromString,
                _registered_method=True)
        self.DeleteObjectStorageWIFConfig = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/DeleteObjectStorageWIFConfig',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteObjectStorageWIFConfigRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteObjectStorageWIFConfigResponse.FromString,
                _registered_method=True)
        self.GetFileSystemSnapshotBucketConfig = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/GetFileSystemSnapshotBucketConfig',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetFileSystemSnapshotBucketConfigRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.FileSystemSnapshotBucketConfig.FromString,
                _registered_method=True)
        self.SetFileSystemSnapshotBucketConfig = channel.unary_unary(
                '/coreweave.sandbox.v1beta2.GatewayService/SetFileSystemSnapshotBucketConfig',
                request_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.SetFileSystemSnapshotBucketConfigRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.FileSystemSnapshotBucketConfig.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """----------------------------------------------------------------------------------
    Service Definition
    ----------------------------------------------------------------------------------

    GatewayService provides sandbox management capabilities.
    """

    def Start(self, request, context):
        """Start launches a new sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop terminates a running sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFileSystemSnapshot(self, request, context):
        """CreateFileSystemSnapshot creates an FSS from a running sandbox without stopping it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileSystemSnapshot(self, request, context):
        """GetFileSystemSnapshot retrieves an org-scoped FSS by id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFileSystemSnapshots(self, request, context):
        """ListFileSystemSnapshots lists org-scoped FSS rows.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFileSystemSnapshot(self, request, context):
        """DeleteFileSystemSnapshot hides an FSS row from future customer Get/List calls.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Get retrieves details about a specific sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """List enumerates sandboxes with optional filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete removes a sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Exec executes a command within a sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFile(self, request, context):
        """AddFile writes (or overwrites) a file inside the sandbox filesystem.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveFile(self, request, context):
        """RetrieveFile retrieves a file's contents from the sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Pause pauses a running sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Resume resumes a paused sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Raw(self, request, context):
        """Raw executes a raw action on a sandbox based on action_type.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObjectStorageWIFConfig(self, request, context):
        """--- Object Storage WIF Config Management ---

        Returns the organization's WIF configuration.
        Derives org_id from the authenticated caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetObjectStorageWIFConfig(self, request, context):
        """Creates or replaces the organization's WIF configuration.
        Derives org_id from the authenticated caller.
        Since there is one config per org, this is an idempotent upsert.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObjectStorageWIFConfig(self, request, context):
        """Deletes the organization's WIF configuration.
        Running sandboxes are unaffected until their OIDC JWT expires.
        New sandbox requests with object_storage_access will be rejected.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileSystemSnapshotBucketConfig(self, request, context):
        """--- File System Snapshot Bucket Config Management ---

        Returns the organization's FSS bucket configuration (org_id derived from the
        authenticated caller). Open to any authenticated org member.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFileSystemSnapshotBucketConfig(self, request, context):
        """Creates or replaces the organization's FSS bucket configuration (idempotent
        full-replace upsert; org_id derived from the caller). Requires the
        sandbox_admin action: changing or clearing the bucket abandons access to
        snapshots stored in the prior bucket.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StartSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StartSandboxResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StopSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StopSandboxResponse.SerializeToString,
            ),
            'CreateFileSystemSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFileSystemSnapshot,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.CreateFileSystemSnapshotRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.CreateFileSystemSnapshotResponse.SerializeToString,
            ),
            'GetFileSystemSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileSystemSnapshot,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetFileSystemSnapshotRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.FileSystemSnapshot.SerializeToString,
            ),
            'ListFileSystemSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFileSystemSnapshots,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListFileSystemSnapshotsRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListFileSystemSnapshotsResponse.SerializeToString,
            ),
            'DeleteFileSystemSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFileSystemSnapshot,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteFileSystemSnapshotRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteFileSystemSnapshotResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetSandboxResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListSandboxesRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListSandboxesResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteSandboxResponse.SerializeToString,
            ),
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ExecSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ExecSandboxResponse.SerializeToString,
            ),
            'AddFile': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFile,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.AddFileSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.AddFileSandboxResponse.SerializeToString,
            ),
            'RetrieveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveFile,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RetrieveFileSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RetrieveFileSandboxResponse.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.PauseSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.PauseSandboxResponse.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ResumeSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ResumeSandboxResponse.SerializeToString,
            ),
            'Raw': grpc.unary_unary_rpc_method_handler(
                    servicer.Raw,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RawSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RawSandboxResponse.SerializeToString,
            ),
            'GetObjectStorageWIFConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjectStorageWIFConfig,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetObjectStorageWIFConfigRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ObjectStorageWIFConfig.SerializeToString,
            ),
            'SetObjectStorageWIFConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetObjectStorageWIFConfig,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.SetObjectStorageWIFConfigRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ObjectStorageWIFConfig.SerializeToString,
            ),
            'DeleteObjectStorageWIFConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObjectStorageWIFConfig,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteObjectStorageWIFConfigRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteObjectStorageWIFConfigResponse.SerializeToString,
            ),
            'GetFileSystemSnapshotBucketConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileSystemSnapshotBucketConfig,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetFileSystemSnapshotBucketConfigRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.FileSystemSnapshotBucketConfig.SerializeToString,
            ),
            'SetFileSystemSnapshotBucketConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFileSystemSnapshotBucketConfig,
                    request_deserializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.SetFileSystemSnapshotBucketConfigRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.FileSystemSnapshotBucketConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coreweave.sandbox.v1beta2.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coreweave.sandbox.v1beta2.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """----------------------------------------------------------------------------------
    Service Definition
    ----------------------------------------------------------------------------------

    GatewayService provides sandbox management capabilities.
    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/Start',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StartSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StartSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/Stop',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StopSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.StopSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFileSystemSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/CreateFileSystemSnapshot',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.CreateFileSystemSnapshotRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.CreateFileSystemSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileSystemSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/GetFileSystemSnapshot',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetFileSystemSnapshotRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.FileSystemSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFileSystemSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/ListFileSystemSnapshots',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListFileSystemSnapshotsRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListFileSystemSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFileSystemSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/DeleteFileSystemSnapshot',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteFileSystemSnapshotRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteFileSystemSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/Get',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/List',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListSandboxesRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ListSandboxesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/Delete',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/Exec',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ExecSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ExecSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/AddFile',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.AddFileSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.AddFileSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/RetrieveFile',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RetrieveFileSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RetrieveFileSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/Pause',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.PauseSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.PauseSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/Resume',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ResumeSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ResumeSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Raw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/Raw',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RawSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.RawSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObjectStorageWIFConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/GetObjectStorageWIFConfig',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetObjectStorageWIFConfigRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ObjectStorageWIFConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetObjectStorageWIFConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/SetObjectStorageWIFConfig',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.SetObjectStorageWIFConfigRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.ObjectStorageWIFConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteObjectStorageWIFConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/DeleteObjectStorageWIFConfig',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteObjectStorageWIFConfigRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.DeleteObjectStorageWIFConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileSystemSnapshotBucketConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/GetFileSystemSnapshotBucketConfig',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.GetFileSystemSnapshotBucketConfigRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.FileSystemSnapshotBucketConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFileSystemSnapshotBucketConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.sandbox.v1beta2.GatewayService/SetFileSystemSnapshotBucketConfig',
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.SetFileSystemSnapshotBucketConfigRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1beta2_dot_gateway__pb2.FileSystemSnapshotBucketConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
