# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: cwsandbox-client
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cwsandbox._proto import sandbox_pb2 as coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2


class SandboxDataPlaneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exec = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxDataPlaneService/Exec',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.FromString,
                )
        self.StreamExec = channel.stream_stream(
                '/coreweave.sandbox.v1.SandboxDataPlaneService/StreamExec',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamResponse.FromString,
                )
        self.StreamLogs = channel.unary_stream(
                '/coreweave.sandbox.v1.SandboxDataPlaneService/StreamLogs',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.StreamLogsRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.LogEntry.FromString,
                )
        self.WriteFile = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxDataPlaneService/WriteFile',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileResponse.FromString,
                )
        self.ReadFile = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxDataPlaneService/ReadFile',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.FromString,
                )


class SandboxDataPlaneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exec(self, request, context):
        """Exec runs a command to completion in a container and returns buffered
        output. Use StreamExec for interactive or large-output commands.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExec(self, request_iterator, context):
        """StreamExec runs a command in a container over a bidirectional stream,
        supporting TTY, stdin, and terminal resize.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """StreamLogs streams a live container's stdout and stderr.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """WriteFile writes a file in a container's filesystem.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """ReadFile reads a file from a container's filesystem.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxDataPlaneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.SerializeToString,
            ),
            'StreamExec': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamExec,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.StreamLogsRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.LogEntry.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coreweave.sandbox.v1.SandboxDataPlaneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SandboxDataPlaneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxDataPlaneService/Exec',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamExec(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/coreweave.sandbox.v1.SandboxDataPlaneService/StreamExec',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/coreweave.sandbox.v1.SandboxDataPlaneService/StreamLogs',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.StreamLogsRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.LogEntry.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxDataPlaneService/WriteFile',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxDataPlaneService/ReadFile',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
