# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: cwsandbox-client
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cwsandbox._proto import sandbox_pb2 as coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2


class SandboxServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSandbox = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/CreateSandbox',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.Sandbox.FromString,
                )
        self.CreateSandboxFromTemplate = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/CreateSandboxFromTemplate',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxFromTemplateRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.Sandbox.FromString,
                )
        self.GetSandbox = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/GetSandbox',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.GetSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.Sandbox.FromString,
                )
        self.ListSandboxes = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/ListSandboxes',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListSandboxesRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListSandboxesResponse.FromString,
                )
        self.DeleteSandbox = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/DeleteSandbox',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.DeleteSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.DeleteSandboxResponse.FromString,
                )
        self.PurgeSandboxes = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/PurgeSandboxes',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.PurgeSandboxesRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.PurgeSandboxesResponse.FromString,
                )
        self.ConnectSandbox = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/ConnectSandbox',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ConnectSandboxRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.SandboxConnection.FromString,
                )
        self.Exec = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/Exec',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.FromString,
                )
        self.StreamExec = channel.stream_stream(
                '/coreweave.sandbox.v1.SandboxService/StreamExec',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamResponse.FromString,
                )
        self.StreamLogs = channel.unary_stream(
                '/coreweave.sandbox.v1.SandboxService/StreamLogs',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.StreamLogsRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.LogEntry.FromString,
                )
        self.WriteFile = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/WriteFile',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileResponse.FromString,
                )
        self.ReadFile = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/ReadFile',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.FromString,
                )
        self.CreateFileSystemSnapshot = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/CreateFileSystemSnapshot',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateFileSystemSnapshotRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.FileSystemSnapshot.FromString,
                )
        self.GetFileSystemSnapshot = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/GetFileSystemSnapshot',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.GetFileSystemSnapshotRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.FileSystemSnapshot.FromString,
                )
        self.ListFileSystemSnapshots = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/ListFileSystemSnapshots',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListFileSystemSnapshotsRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListFileSystemSnapshotsResponse.FromString,
                )
        self.DeleteFileSystemSnapshot = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxService/DeleteFileSystemSnapshot',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.DeleteFileSystemSnapshotRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.FileSystemSnapshot.FromString,
                )


class SandboxServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSandbox(self, request, context):
        """CreateSandbox launches a sandbox from a complete SandboxSpec (AIP-133).
        Returns immediately with the sandbox in STATE_CREATING; poll GetSandbox for
        STATE_RUNNING / terminal states. To create from an org template, use
        CreateSandboxFromTemplate.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSandboxFromTemplate(self, request, context):
        """CreateSandboxFromTemplate launches a sandbox by merging an organization-
        scoped SandboxTemplate with optional replace-on-presence overrides
        (AIP-136 custom method). Returns immediately with the sandbox in
        STATE_CREATING; poll GetSandbox for STATE_RUNNING / terminal states.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandbox(self, request, context):
        """GetSandbox returns the current state of a sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSandboxes(self, request, context):
        """ListSandboxes lists the caller's sandboxes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSandbox(self, request, context):
        """DeleteSandbox terminates a sandbox. Optionally drains gracefully and/or
        snapshots its volumes on the way down.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeSandboxes(self, request, context):
        """PurgeSandboxes terminates active sandboxes matching the selected scope
        (criteria-based bulk delete). It terminates the matched sandboxes by default;
        set dry_run=true to instead report how many sandboxes would be purged without
        terminating anything. The request must specify exactly one scope selector:
        tags for targeted purge, or purge_all=true for every in-scope sandbox. Scope
        follows DeleteSandbox: always within the caller's organization, restricted to
        the caller's own sandboxes unless the caller holds the sandbox_admin action,
        which purges across the organization. Only active sandboxes are ever in
        scope; terminal ones are skipped. Termination is best-effort — ids that fail
        to terminate are returned in failed_sandbox_ids. If the RPC itself returns an
        error after matching begins, some sandboxes may already have been terminated
        and no partial response body is returned; retry the same filter to converge.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectSandbox(self, request, context):
        """ConnectSandbox issues short-lived client credentials and returns
        the direct data-plane endpoint for a running sandbox. The client generates
        and retains the private key; this method accepts only its signed CSR.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Exec runs a command to completion in a container and returns buffered
        output. Use StreamExec for interactive or large-output commands.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExec(self, request_iterator, context):
        """StreamExec runs a command in a container over a bidirectional stream,
        supporting TTY, stdin, and terminal resize.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """StreamLogs streams a live container's stdout/stderr, supporting follow,
        tail, since-time, resume, and terminal in-band stream errors. A terminal or
        terminating sandbox fails with CWSANDBOX_SANDBOX_NOT_RUNNING.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """WriteFile writes (creates or overwrites) a file in a container's filesystem.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """ReadFile reads a file from a container's filesystem.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFileSystemSnapshot(self, request, context):
        """CreateFileSystemSnapshot snapshots a volume of a RUNNING sandbox to durable
        storage. Returns the snapshot in SNAPSHOT_STATE_CREATING; poll Get.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileSystemSnapshot(self, request, context):
        """GetFileSystemSnapshot returns snapshot metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFileSystemSnapshots(self, request, context):
        """ListFileSystemSnapshots lists the caller's snapshots.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFileSystemSnapshot(self, request, context):
        """DeleteFileSystemSnapshot deletes a snapshot. Sandboxes restored from it are
        unaffected.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandbox,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.Sandbox.SerializeToString,
            ),
            'CreateSandboxFromTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandboxFromTemplate,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxFromTemplateRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.Sandbox.SerializeToString,
            ),
            'GetSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandbox,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.GetSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.Sandbox.SerializeToString,
            ),
            'ListSandboxes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSandboxes,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListSandboxesRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListSandboxesResponse.SerializeToString,
            ),
            'DeleteSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSandbox,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.DeleteSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.DeleteSandboxResponse.SerializeToString,
            ),
            'PurgeSandboxes': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeSandboxes,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.PurgeSandboxesRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.PurgeSandboxesResponse.SerializeToString,
            ),
            'ConnectSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectSandbox,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ConnectSandboxRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.SandboxConnection.SerializeToString,
            ),
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.SerializeToString,
            ),
            'StreamExec': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamExec,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.StreamLogsRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.LogEntry.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.SerializeToString,
            ),
            'CreateFileSystemSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFileSystemSnapshot,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateFileSystemSnapshotRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.FileSystemSnapshot.SerializeToString,
            ),
            'GetFileSystemSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileSystemSnapshot,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.GetFileSystemSnapshotRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.FileSystemSnapshot.SerializeToString,
            ),
            'ListFileSystemSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFileSystemSnapshots,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListFileSystemSnapshotsRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListFileSystemSnapshotsResponse.SerializeToString,
            ),
            'DeleteFileSystemSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFileSystemSnapshot,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.DeleteFileSystemSnapshotRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.FileSystemSnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coreweave.sandbox.v1.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/CreateSandbox',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.Sandbox.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSandboxFromTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/CreateSandboxFromTemplate',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxFromTemplateRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.Sandbox.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/GetSandbox',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.GetSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.Sandbox.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/ListSandboxes',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListSandboxesRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListSandboxesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/DeleteSandbox',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.DeleteSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.DeleteSandboxResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurgeSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/PurgeSandboxes',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.PurgeSandboxesRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.PurgeSandboxesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/ConnectSandbox',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ConnectSandboxRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.SandboxConnection.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/Exec',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamExec(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/coreweave.sandbox.v1.SandboxService/StreamExec',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/coreweave.sandbox.v1.SandboxService/StreamLogs',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.StreamLogsRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.LogEntry.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/WriteFile',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.WriteFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/ReadFile',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateFileSystemSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/CreateFileSystemSnapshot',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateFileSystemSnapshotRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.FileSystemSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileSystemSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/GetFileSystemSnapshot',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.GetFileSystemSnapshotRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.FileSystemSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFileSystemSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/ListFileSystemSnapshots',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListFileSystemSnapshotsRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.ListFileSystemSnapshotsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFileSystemSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxService/DeleteFileSystemSnapshot',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.DeleteFileSystemSnapshotRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2.FileSystemSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
