# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: cwsandbox-client
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coreweave/sandbox/v1/sandbox_data_plane.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cwsandbox._proto import sandbox_pb2 as coreweave_dot_sandbox_dot_v1_dot_sandbox__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-coreweave/sandbox/v1/sandbox_data_plane.proto\x12\x14\x63oreweave.sandbox.v1\x1a\"coreweave/sandbox/v1/sandbox.proto\x1a\x1cgoogle/api/annotations.proto2\xe3\x05\n\x17SandboxDataPlaneService\x12\x8a\x01\n\x04\x45xec\x12!.coreweave.sandbox.v1.ExecRequest\x1a\".coreweave.sandbox.v1.ExecResponse\";\x82\xd3\xe4\x93\x02\x35\"0/v1/sandboxDataPlane/sandboxes/{sandbox_id}:exec:\x01*\x12\x63\n\nStreamExec\x12\'.coreweave.sandbox.v1.ExecStreamRequest\x1a(.coreweave.sandbox.v1.ExecStreamResponse(\x01\x30\x01\x12\x9a\x01\n\nStreamLogs\x12\'.coreweave.sandbox.v1.StreamLogsRequest\x1a\x1e.coreweave.sandbox.v1.LogEntry\"A\x82\xd3\xe4\x93\x02;\"6/v1/sandboxDataPlane/sandboxes/{sandbox_id}:streamLogs:\x01*0\x01\x12\x9e\x01\n\tWriteFile\x12&.coreweave.sandbox.v1.WriteFileRequest\x1a\'.coreweave.sandbox.v1.WriteFileResponse\"@\x82\xd3\xe4\x93\x02:\"5/v1/sandboxDataPlane/sandboxes/{sandbox_id}:writeFile:\x01*\x12\x97\x01\n\x08ReadFile\x12%.coreweave.sandbox.v1.ReadFileRequest\x1a&.coreweave.sandbox.v1.ReadFileResponse\"<\x82\xd3\xe4\x93\x02\x36\x12\x34/v1/sandboxDataPlane/sandboxes/{sandbox_id}:readFileBAZ?github.com/coreweave/sandbox/api/coreweave/sandbox/v1;sandboxv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coreweave.sandbox.v1.sandbox_data_plane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/coreweave/sandbox/api/coreweave/sandbox/v1;sandboxv1'
  _globals['_SANDBOXDATAPLANESERVICE'].methods_by_name['Exec']._loaded_options = None
  _globals['_SANDBOXDATAPLANESERVICE'].methods_by_name['Exec']._serialized_options = b'\202\323\344\223\0025\"0/v1/sandboxDataPlane/sandboxes/{sandbox_id}:exec:\001*'
  _globals['_SANDBOXDATAPLANESERVICE'].methods_by_name['StreamLogs']._loaded_options = None
  _globals['_SANDBOXDATAPLANESERVICE'].methods_by_name['StreamLogs']._serialized_options = b'\202\323\344\223\002;\"6/v1/sandboxDataPlane/sandboxes/{sandbox_id}:streamLogs:\001*'
  _globals['_SANDBOXDATAPLANESERVICE'].methods_by_name['WriteFile']._loaded_options = None
  _globals['_SANDBOXDATAPLANESERVICE'].methods_by_name['WriteFile']._serialized_options = b'\202\323\344\223\002:\"5/v1/sandboxDataPlane/sandboxes/{sandbox_id}:writeFile:\001*'
  _globals['_SANDBOXDATAPLANESERVICE'].methods_by_name['ReadFile']._loaded_options = None
  _globals['_SANDBOXDATAPLANESERVICE'].methods_by_name['ReadFile']._serialized_options = b'\202\323\344\223\0026\0224/v1/sandboxDataPlane/sandboxes/{sandbox_id}:readFile'
  _globals['_SANDBOXDATAPLANESERVICE']._serialized_start=138
  _globals['_SANDBOXDATAPLANESERVICE']._serialized_end=877
# @@protoc_insertion_point(module_scope)
