# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: cwsandbox-client
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cwsandbox._proto import sandbox_template_pb2 as coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SandboxTemplateServiceStub(object):
    """SandboxTemplateService provides CRUD for org-scoped SandboxTemplate resources.
    Write RPCs require sandbox_admin; Get/List are available to sandbox_user for
    active templates. Soft-deleted templates are visible to admins only when
    show_deleted is set.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSandboxTemplate = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxTemplateService/CreateSandboxTemplate',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.CreateSandboxTemplateRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.SandboxTemplate.FromString,
                )
        self.GetSandboxTemplate = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxTemplateService/GetSandboxTemplate',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.GetSandboxTemplateRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.SandboxTemplate.FromString,
                )
        self.ListSandboxTemplates = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxTemplateService/ListSandboxTemplates',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.ListSandboxTemplatesRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.ListSandboxTemplatesResponse.FromString,
                )
        self.UpdateSandboxTemplate = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxTemplateService/UpdateSandboxTemplate',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.UpdateSandboxTemplateRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.SandboxTemplate.FromString,
                )
        self.DeleteSandboxTemplate = channel.unary_unary(
                '/coreweave.sandbox.v1.SandboxTemplateService/DeleteSandboxTemplate',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.DeleteSandboxTemplateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class SandboxTemplateServiceServicer(object):
    """SandboxTemplateService provides CRUD for org-scoped SandboxTemplate resources.
    Write RPCs require sandbox_admin; Get/List are available to sandbox_user for
    active templates. Soft-deleted templates are visible to admins only when
    show_deleted is set.
    """

    def CreateSandboxTemplate(self, request, context):
        """CreateSandboxTemplate creates a new template. Requires sandbox_admin.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandboxTemplate(self, request, context):
        """GetSandboxTemplate returns a template by UUID or org-unique display_name.
        Soft-deleted templates require show_deleted and sandbox_admin.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSandboxTemplates(self, request, context):
        """ListSandboxTemplates lists templates in the caller's tenant organization.
        Soft-deleted rows are omitted unless show_deleted is set (admin only).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSandboxTemplate(self, request, context):
        """UpdateSandboxTemplate patches a template. Requires sandbox_admin.
        Each successful update increments revision.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSandboxTemplate(self, request, context):
        """DeleteSandboxTemplate soft-deletes a template. Requires sandbox_admin.
        Existing sandboxes are unaffected; new creates cannot select the template.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxTemplateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSandboxTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandboxTemplate,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.CreateSandboxTemplateRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.SandboxTemplate.SerializeToString,
            ),
            'GetSandboxTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandboxTemplate,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.GetSandboxTemplateRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.SandboxTemplate.SerializeToString,
            ),
            'ListSandboxTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSandboxTemplates,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.ListSandboxTemplatesRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.ListSandboxTemplatesResponse.SerializeToString,
            ),
            'UpdateSandboxTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSandboxTemplate,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.UpdateSandboxTemplateRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.SandboxTemplate.SerializeToString,
            ),
            'DeleteSandboxTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSandboxTemplate,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.DeleteSandboxTemplateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coreweave.sandbox.v1.SandboxTemplateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SandboxTemplateService(object):
    """SandboxTemplateService provides CRUD for org-scoped SandboxTemplate resources.
    Write RPCs require sandbox_admin; Get/List are available to sandbox_user for
    active templates. Soft-deleted templates are visible to admins only when
    show_deleted is set.
    """

    @staticmethod
    def CreateSandboxTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxTemplateService/CreateSandboxTemplate',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.CreateSandboxTemplateRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.SandboxTemplate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSandboxTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxTemplateService/GetSandboxTemplate',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.GetSandboxTemplateRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.SandboxTemplate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSandboxTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxTemplateService/ListSandboxTemplates',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.ListSandboxTemplatesRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.ListSandboxTemplatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSandboxTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxTemplateService/UpdateSandboxTemplate',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.UpdateSandboxTemplateRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.SandboxTemplate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSandboxTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SandboxTemplateService/DeleteSandboxTemplate',
            coreweave_dot_sandbox_dot_v1_dot_sandbox__template__pb2.DeleteSandboxTemplateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
