# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: cwsandbox-client
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cwsandbox._proto import secrets_pb2 as coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2


class SecretStoreServiceStub(object):
    """-----------------------------------------------------------------------------
    SecretStoreService
    -----------------------------------------------------------------------------
    Manages org-level secret store configurations. Organization is derived from
    the caller's auth context (not the URL path).

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSecretStore = channel.unary_unary(
                '/coreweave.aviato.v1beta1.SecretStoreService/CreateSecretStore',
                request_serializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.CreateSecretStoreRequest.SerializeToString,
                response_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.CreateSecretStoreResponse.FromString,
                _registered_method=True)
        self.GetSecretStore = channel.unary_unary(
                '/coreweave.aviato.v1beta1.SecretStoreService/GetSecretStore',
                request_serializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.GetSecretStoreRequest.SerializeToString,
                response_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.GetSecretStoreResponse.FromString,
                _registered_method=True)
        self.ListSecretStores = channel.unary_unary(
                '/coreweave.aviato.v1beta1.SecretStoreService/ListSecretStores',
                request_serializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.ListSecretStoresRequest.SerializeToString,
                response_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.ListSecretStoresResponse.FromString,
                _registered_method=True)
        self.DeleteSecretStore = channel.unary_unary(
                '/coreweave.aviato.v1beta1.SecretStoreService/DeleteSecretStore',
                request_serializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.DeleteSecretStoreRequest.SerializeToString,
                response_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.DeleteSecretStoreResponse.FromString,
                _registered_method=True)


class SecretStoreServiceServicer(object):
    """-----------------------------------------------------------------------------
    SecretStoreService
    -----------------------------------------------------------------------------
    Manages org-level secret store configurations. Organization is derived from
    the caller's auth context (not the URL path).

    """

    def CreateSecretStore(self, request, context):
        """CreateSecretStore registers a new secret store for the caller's organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecretStore(self, request, context):
        """GetSecretStore retrieves a secret store by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecretStores(self, request, context):
        """ListSecretStores lists secret stores for the caller's organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSecretStore(self, request, context):
        """DeleteSecretStore removes a secret store by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecretStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSecretStore': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSecretStore,
                    request_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.CreateSecretStoreRequest.FromString,
                    response_serializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.CreateSecretStoreResponse.SerializeToString,
            ),
            'GetSecretStore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecretStore,
                    request_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.GetSecretStoreRequest.FromString,
                    response_serializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.GetSecretStoreResponse.SerializeToString,
            ),
            'ListSecretStores': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecretStores,
                    request_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.ListSecretStoresRequest.FromString,
                    response_serializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.ListSecretStoresResponse.SerializeToString,
            ),
            'DeleteSecretStore': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSecretStore,
                    request_deserializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.DeleteSecretStoreRequest.FromString,
                    response_serializer=coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.DeleteSecretStoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coreweave.aviato.v1beta1.SecretStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coreweave.aviato.v1beta1.SecretStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecretStoreService(object):
    """-----------------------------------------------------------------------------
    SecretStoreService
    -----------------------------------------------------------------------------
    Manages org-level secret store configurations. Organization is derived from
    the caller's auth context (not the URL path).

    """

    @staticmethod
    def CreateSecretStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.aviato.v1beta1.SecretStoreService/CreateSecretStore',
            coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.CreateSecretStoreRequest.SerializeToString,
            coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.CreateSecretStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSecretStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.aviato.v1beta1.SecretStoreService/GetSecretStore',
            coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.GetSecretStoreRequest.SerializeToString,
            coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.GetSecretStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSecretStores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.aviato.v1beta1.SecretStoreService/ListSecretStores',
            coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.ListSecretStoresRequest.SerializeToString,
            coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.ListSecretStoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSecretStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreweave.aviato.v1beta1.SecretStoreService/DeleteSecretStore',
            coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.DeleteSecretStoreRequest.SerializeToString,
            coreweave_dot_aviato_dot_v1beta1_dot_secrets__pb2.DeleteSecretStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
