# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: cwsandbox-client
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cwsandbox._proto import settings_pb2 as coreweave_dot_sandbox_dot_v1_dot_settings__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SettingsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObjectStorageWifConfig = channel.unary_unary(
                '/coreweave.sandbox.v1.SettingsService/GetObjectStorageWifConfig',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.GetObjectStorageWifConfigRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ObjectStorageWifConfig.FromString,
                )
        self.UpdateObjectStorageWifConfig = channel.unary_unary(
                '/coreweave.sandbox.v1.SettingsService/UpdateObjectStorageWifConfig',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.UpdateObjectStorageWifConfigRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ObjectStorageWifConfig.FromString,
                )
        self.DeleteObjectStorageWifConfig = channel.unary_unary(
                '/coreweave.sandbox.v1.SettingsService/DeleteObjectStorageWifConfig',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.DeleteObjectStorageWifConfigRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetFileSystemSnapshotBucketConfig = channel.unary_unary(
                '/coreweave.sandbox.v1.SettingsService/GetFileSystemSnapshotBucketConfig',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.GetFileSystemSnapshotBucketConfigRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.FileSystemSnapshotBucketConfig.FromString,
                )
        self.UpdateFileSystemSnapshotBucketConfig = channel.unary_unary(
                '/coreweave.sandbox.v1.SettingsService/UpdateFileSystemSnapshotBucketConfig',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.UpdateFileSystemSnapshotBucketConfigRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.FileSystemSnapshotBucketConfig.FromString,
                )
        self.CreateSecretStore = channel.unary_unary(
                '/coreweave.sandbox.v1.SettingsService/CreateSecretStore',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.CreateSecretStoreRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.SecretStore.FromString,
                )
        self.GetSecretStore = channel.unary_unary(
                '/coreweave.sandbox.v1.SettingsService/GetSecretStore',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.GetSecretStoreRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.SecretStore.FromString,
                )
        self.ListSecretStores = channel.unary_unary(
                '/coreweave.sandbox.v1.SettingsService/ListSecretStores',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ListSecretStoresRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ListSecretStoresResponse.FromString,
                )
        self.UpdateSecretStore = channel.unary_unary(
                '/coreweave.sandbox.v1.SettingsService/UpdateSecretStore',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.UpdateSecretStoreRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.SecretStore.FromString,
                )
        self.DeleteSecretStore = channel.unary_unary(
                '/coreweave.sandbox.v1.SettingsService/DeleteSecretStore',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.DeleteSecretStoreRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class SettingsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetObjectStorageWifConfig(self, request, context):
        """GetObjectStorageWifConfig returns the org's object-storage WIF config.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateObjectStorageWifConfig(self, request, context):
        """UpdateObjectStorageWifConfig creates or updates the org's WIF config.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObjectStorageWifConfig(self, request, context):
        """DeleteObjectStorageWifConfig removes the org's WIF config; afterward new
        object_storage_access requests are rejected (distinct from enabled=false).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileSystemSnapshotBucketConfig(self, request, context):
        """GetFileSystemSnapshotBucketConfig returns the org's FSS bucket config.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFileSystemSnapshotBucketConfig(self, request, context):
        """UpdateFileSystemSnapshotBucketConfig sets the org's FSS bucket config. An
        empty bucket_name reverts the org to CoreWeave-managed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSecretStore(self, request, context):
        """CreateSecretStore registers a secret store for the caller's organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecretStore(self, request, context):
        """GetSecretStore returns a secret store by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecretStores(self, request, context):
        """ListSecretStores lists the caller's secret stores.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSecretStore(self, request, context):
        """UpdateSecretStore updates a secret store (identified by secret_store.name).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSecretStore(self, request, context):
        """DeleteSecretStore removes a secret store by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettingsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObjectStorageWifConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjectStorageWifConfig,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.GetObjectStorageWifConfigRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ObjectStorageWifConfig.SerializeToString,
            ),
            'UpdateObjectStorageWifConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateObjectStorageWifConfig,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.UpdateObjectStorageWifConfigRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ObjectStorageWifConfig.SerializeToString,
            ),
            'DeleteObjectStorageWifConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObjectStorageWifConfig,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.DeleteObjectStorageWifConfigRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetFileSystemSnapshotBucketConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileSystemSnapshotBucketConfig,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.GetFileSystemSnapshotBucketConfigRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.FileSystemSnapshotBucketConfig.SerializeToString,
            ),
            'UpdateFileSystemSnapshotBucketConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFileSystemSnapshotBucketConfig,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.UpdateFileSystemSnapshotBucketConfigRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.FileSystemSnapshotBucketConfig.SerializeToString,
            ),
            'CreateSecretStore': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSecretStore,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.CreateSecretStoreRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.SecretStore.SerializeToString,
            ),
            'GetSecretStore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecretStore,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.GetSecretStoreRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.SecretStore.SerializeToString,
            ),
            'ListSecretStores': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecretStores,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ListSecretStoresRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ListSecretStoresResponse.SerializeToString,
            ),
            'UpdateSecretStore': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSecretStore,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.UpdateSecretStoreRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.SecretStore.SerializeToString,
            ),
            'DeleteSecretStore': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSecretStore,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_settings__pb2.DeleteSecretStoreRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coreweave.sandbox.v1.SettingsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SettingsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetObjectStorageWifConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SettingsService/GetObjectStorageWifConfig',
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.GetObjectStorageWifConfigRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ObjectStorageWifConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateObjectStorageWifConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SettingsService/UpdateObjectStorageWifConfig',
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.UpdateObjectStorageWifConfigRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ObjectStorageWifConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteObjectStorageWifConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SettingsService/DeleteObjectStorageWifConfig',
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.DeleteObjectStorageWifConfigRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileSystemSnapshotBucketConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SettingsService/GetFileSystemSnapshotBucketConfig',
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.GetFileSystemSnapshotBucketConfigRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.FileSystemSnapshotBucketConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateFileSystemSnapshotBucketConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SettingsService/UpdateFileSystemSnapshotBucketConfig',
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.UpdateFileSystemSnapshotBucketConfigRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.FileSystemSnapshotBucketConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSecretStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SettingsService/CreateSecretStore',
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.CreateSecretStoreRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.SecretStore.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSecretStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SettingsService/GetSecretStore',
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.GetSecretStoreRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.SecretStore.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSecretStores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SettingsService/ListSecretStores',
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ListSecretStoresRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.ListSecretStoresResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSecretStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SettingsService/UpdateSecretStore',
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.UpdateSecretStoreRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.SecretStore.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSecretStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.SettingsService/DeleteSecretStore',
            coreweave_dot_sandbox_dot_v1_dot_settings__pb2.DeleteSecretStoreRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
