# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: cwsandbox-client
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ExecStreamRequest(google.protobuf.message.Message):
    """-----------------------------------------------------------------------------
    Exec Streaming Messages (Client API)
    -----------------------------------------------------------------------------

    ExecStreamRequest is sent by client to initiate exec or send stdin data.
    The first message must be an init message, followed by optional stdin,
    resize, and close messages.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INIT_FIELD_NUMBER: builtins.int
    STDIN_FIELD_NUMBER: builtins.int
    RESIZE_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    @property
    def init(self) -> global___ExecStreamInit:
        """Initial request to start command execution.
        Must be the first message sent on the stream.
        """
    @property
    def stdin(self) -> global___ExecStreamData:
        """Stdin data to send to the executing process.
        Can be sent multiple times after init.
        """
    @property
    def resize(self) -> global___ExecStreamResize:
        """Terminal resize event for TTY sessions.
        Can be sent multiple times after init.
        """
    @property
    def close(self) -> global___ExecStreamClose:
        """Signal to close the stdin stream.
        Process will continue running, but will receive EOF on stdin.
        """
    def __init__(
        self,
        *,
        init: global___ExecStreamInit | None = ...,
        stdin: global___ExecStreamData | None = ...,
        resize: global___ExecStreamResize | None = ...,
        close: global___ExecStreamClose | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["close", b"close", "init", b"init", "request", b"request", "resize", b"resize", "stdin", b"stdin"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["close", b"close", "init", b"init", "request", b"request", "resize", b"resize", "stdin", b"stdin"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["request", b"request"]) -> typing_extensions.Literal["init", "stdin", "resize", "close"] | None: ...

global___ExecStreamRequest = ExecStreamRequest

@typing_extensions.final
class ExecStreamInit(google.protobuf.message.Message):
    """ExecStreamInit initiates a streaming exec session."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class EnvEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SANDBOX_ID_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    TTY_FIELD_NUMBER: builtins.int
    TTY_WIDTH_FIELD_NUMBER: builtins.int
    TTY_HEIGHT_FIELD_NUMBER: builtins.int
    ENV_FIELD_NUMBER: builtins.int
    RESUME_SESSION_ID_FIELD_NUMBER: builtins.int
    sandbox_id: builtins.str
    """The sandbox ID where the command should be executed."""
    @property
    def command(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Command and arguments to execute.
        The first element is the command, subsequent elements are arguments.
        """
    tty: builtins.bool
    """Enable TTY (pseudo-terminal) mode.
    When enabled, stdout and stderr are combined into a single stream.
    """
    tty_width: builtins.int
    """Initial terminal width in columns (for TTY mode)."""
    tty_height: builtins.int
    """Initial terminal height in rows (for TTY mode)."""
    @property
    def env(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Environment variables to set for the command execution."""
    resume_session_id: builtins.str
    """Resume an existing exec session that was interrupted (e.g. the client lost
    its connection during a Gateway roll). A non-empty value switches the
    request into "resume mode": the server reattaches the caller to the
    live session on the owning Runner and IGNORES command/tty/tty_width/
    tty_height/env. Sandbox_id is still validated for authorization.

    The server MUST reject a request that combines resume_session_id with
    non-empty command, non-default tty/tty_width/tty_height, or non-empty
    env with INVALID_ARGUMENT — these field combinations are protocol
    errors, not silent overrides. (The reject keeps "init mode" and
    "resume mode" semantically exclusive so a future tightening of the
    contract doesn't break existing SDKs that rely on silent ignore.)

    Applies to all exec sessions (TTY and non-TTY). The session_id was
    returned in StreamingExecReady.session_id on the original stream. If
    the session is no longer present (lost, expired, or torn down) the
    server returns ExecStreamError{code: "SESSION_NOT_FOUND"} and the
    client should fall back to a fresh init.
    """
    def __init__(
        self,
        *,
        sandbox_id: builtins.str = ...,
        command: collections.abc.Iterable[builtins.str] | None = ...,
        tty: builtins.bool = ...,
        tty_width: builtins.int = ...,
        tty_height: builtins.int = ...,
        env: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        resume_session_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["command", b"command", "env", b"env", "resume_session_id", b"resume_session_id", "sandbox_id", b"sandbox_id", "tty", b"tty", "tty_height", b"tty_height", "tty_width", b"tty_width"]) -> None: ...

global___ExecStreamInit = ExecStreamInit

@typing_extensions.final
class ExecStreamData(google.protobuf.message.Message):
    """ExecStreamData carries stdin data to send to the executing process."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    """Raw stdin bytes to send to the process."""
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data"]) -> None: ...

global___ExecStreamData = ExecStreamData

@typing_extensions.final
class ExecStreamResize(google.protobuf.message.Message):
    """ExecStreamResize signals a terminal resize event for TTY sessions."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    width: builtins.int
    """New terminal width in columns."""
    height: builtins.int
    """New terminal height in rows."""
    def __init__(
        self,
        *,
        width: builtins.int = ...,
        height: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["height", b"height", "width", b"width"]) -> None: ...

global___ExecStreamResize = ExecStreamResize

@typing_extensions.final
class ExecStreamClose(google.protobuf.message.Message):
    """ExecStreamClose signals that the client is closing stdin.
    The process will receive EOF on stdin but will continue executing.
    The stream will continue to deliver stdout/stderr until the process exits.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ExecStreamClose = ExecStreamClose

@typing_extensions.final
class StreamingExecReady(google.protobuf.message.Message):
    """StreamingExecReady signals that stdin is ready to receive data.
    Sent after SPDY connection is established and the exec session is ready.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    READY_AT_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    @property
    def ready_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp when the exec session became ready for input."""
    session_id: builtins.str
    """Server-issued opaque session identifier. Sent exactly once per
    underlying Runner session: on a fresh init it accompanies the first
    StreamingExecReady; on a successful resume the server does NOT
    re-send a Ready frame (the existing session is already running), so
    the client should retain the session_id it received on the original
    stream. The client SHOULD persist this for the lifetime of the
    stream and pass it as ExecStreamInit.resume_session_id on a
    subsequent stream if the original is interrupted, to reattach to
    the live session instead of re-executing the command.
    """
    def __init__(
        self,
        *,
        ready_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        session_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ready_at", b"ready_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ready_at", b"ready_at", "session_id", b"session_id"]) -> None: ...

global___StreamingExecReady = StreamingExecReady

@typing_extensions.final
class ExecStreamResponse(google.protobuf.message.Message):
    """ExecStreamResponse is sent by server with stdout/stderr/status updates."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUTPUT_FIELD_NUMBER: builtins.int
    EXIT_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    READY_FIELD_NUMBER: builtins.int
    @property
    def output(self) -> global___ExecStreamOutput:
        """A chunk of stdout or stderr output from the process."""
    @property
    def exit(self) -> global___ExecStreamExit:
        """Process exit notification with exit code.
        This is the final message for a successful execution.
        """
    @property
    def error(self) -> global___ExecStreamError:
        """Error during execution.
        This is the final message for a failed execution.
        """
    @property
    def ready(self) -> global___StreamingExecReady:
        """Signal that the exec session is ready for stdin input.
        Sent after SPDY connection is established.
        """
    def __init__(
        self,
        *,
        output: global___ExecStreamOutput | None = ...,
        exit: global___ExecStreamExit | None = ...,
        error: global___ExecStreamError | None = ...,
        ready: global___StreamingExecReady | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error", b"error", "exit", b"exit", "output", b"output", "ready", b"ready", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error", "exit", b"exit", "output", b"output", "ready", b"ready", "response", b"response"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["response", b"response"]) -> typing_extensions.Literal["output", "exit", "error", "ready"] | None: ...

global___ExecStreamResponse = ExecStreamResponse

@typing_extensions.final
class ExecStreamOutput(google.protobuf.message.Message):
    """ExecStreamOutput carries a chunk of stdout or stderr data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _StreamType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StreamTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ExecStreamOutput._StreamType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STREAM_TYPE_UNSPECIFIED: ExecStreamOutput._StreamType.ValueType  # 0
        """Unspecified stream type (should not be used)."""
        STREAM_TYPE_STDOUT: ExecStreamOutput._StreamType.ValueType  # 1
        """Standard output stream."""
        STREAM_TYPE_STDERR: ExecStreamOutput._StreamType.ValueType  # 2
        """Standard error stream."""

    class StreamType(_StreamType, metaclass=_StreamTypeEnumTypeWrapper):
        """The type of output stream."""

    STREAM_TYPE_UNSPECIFIED: ExecStreamOutput.StreamType.ValueType  # 0
    """Unspecified stream type (should not be used)."""
    STREAM_TYPE_STDOUT: ExecStreamOutput.StreamType.ValueType  # 1
    """Standard output stream."""
    STREAM_TYPE_STDERR: ExecStreamOutput.StreamType.ValueType  # 2
    """Standard error stream."""

    STREAM_TYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    stream_type: global___ExecStreamOutput.StreamType.ValueType
    """The type of this output (stdout or stderr).
    In TTY mode, all output is sent as STDOUT.
    """
    data: builtins.bytes
    """Raw output bytes."""
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp when this output was captured."""
    def __init__(
        self,
        *,
        stream_type: global___ExecStreamOutput.StreamType.ValueType = ...,
        data: builtins.bytes = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "stream_type", b"stream_type", "timestamp", b"timestamp"]) -> None: ...

global___ExecStreamOutput = ExecStreamOutput

@typing_extensions.final
class ExecStreamExit(google.protobuf.message.Message):
    """ExecStreamExit signals that the process has completed execution."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXIT_CODE_FIELD_NUMBER: builtins.int
    COMPLETED_AT_FIELD_NUMBER: builtins.int
    exit_code: builtins.int
    """The exit code of the process.
    0 indicates success, non-zero indicates an error.
    """
    @property
    def completed_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp when the process completed."""
    def __init__(
        self,
        *,
        exit_code: builtins.int = ...,
        completed_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["completed_at", b"completed_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["completed_at", b"completed_at", "exit_code", b"exit_code"]) -> None: ...

global___ExecStreamExit = ExecStreamExit

@typing_extensions.final
class ExecStreamError(google.protobuf.message.Message):
    """ExecStreamError indicates an error during execution. Every value of
    ExecStreamError is terminal: it is the final message on the stream
    and the client MUST NOT attempt to consume additional frames after
    receiving it. The `code` field tells the client what shape its next
    init (if any) should take.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    message: builtins.str
    """Human-readable error message."""
    code: builtins.str
    """Error code for programmatic error handling. Each documented code
    ends with the prescribed client retry shape (no retry / fresh init
    / resume init).
    Examples:
      "SANDBOX_NOT_FOUND"     — terminal; no retry.
      "EXEC_FAILED"           — terminal; no retry (the command itself failed).
      "PERMISSION_DENIED"     — terminal; no retry.
      "RUNNER_UNAVAILABLE"    — transient; retry with FRESH init (no resume,
                                exec state did not survive).
      "RUNNER_DRAINING"       — transient; retry with FRESH init (exec state
                                cannot cross a Runner roll).
      "SESSION_NOT_FOUND"     — resume_session_id is unknown or expired;
                                retry with FRESH init.
    """
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        code: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "message", b"message"]) -> None: ...

global___ExecStreamError = ExecStreamError

@typing_extensions.final
class LogStreamRequest(google.protobuf.message.Message):
    """-----------------------------------------------------------------------------
    Log Streaming Messages (Client API)
    -----------------------------------------------------------------------------

    LogStreamRequest is sent by client to initiate or control log streaming.
    The first message must be an init message, optionally followed by a close message.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INIT_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    @property
    def init(self) -> global___LogStreamInit:
        """Initial request to start log streaming.
        Must be the first message sent on the stream.
        """
    @property
    def close(self) -> global___LogStreamClose:
        """Signal to close the log stream.
        In follow mode, this stops tailing new logs.
        """
    def __init__(
        self,
        *,
        init: global___LogStreamInit | None = ...,
        close: global___LogStreamClose | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["close", b"close", "init", b"init", "request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["close", b"close", "init", b"init", "request", b"request"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["request", b"request"]) -> typing_extensions.Literal["init", "close"] | None: ...

global___LogStreamRequest = LogStreamRequest

@typing_extensions.final
class LogStreamInit(google.protobuf.message.Message):
    """LogStreamInit initiates a log streaming session."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SANDBOX_ID_FIELD_NUMBER: builtins.int
    FOLLOW_FIELD_NUMBER: builtins.int
    TAIL_LINES_FIELD_NUMBER: builtins.int
    SINCE_TIME_FIELD_NUMBER: builtins.int
    TIMESTAMPS_FIELD_NUMBER: builtins.int
    RESUME_SESSION_ID_FIELD_NUMBER: builtins.int
    RESUME_OFFSET_FIELD_NUMBER: builtins.int
    sandbox_id: builtins.str
    """The sandbox ID whose logs should be streamed."""
    follow: builtins.bool
    """Follow mode - continue streaming new logs as they are generated (like tail -f).
    If false, returns existing logs and closes the stream.
    """
    tail_lines: builtins.int
    """Number of lines to retrieve from the end of the logs.
    If not specified and follow is false, retrieves all available logs.
    """
    @property
    def since_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Only return logs after this timestamp."""
    timestamps: builtins.bool
    """Include timestamps in the log output."""
    resume_session_id: builtins.str
    """Resume an existing FOLLOW-MODE log session. A non-empty value switches
    the request into "resume mode": the server reattaches to the live
    session on the owning Runner and replays from resume_offset onward
    (bounded by the per-session replay window). When set, all other
    fields except sandbox_id are ignored.

    The server MUST reject a request that combines resume_session_id
    with follow=false (the underlying session only exists for follow
    mode) or with non-default tail_lines / since_time / timestamps with
    INVALID_ARGUMENT.

    If the session is no longer present (lost, expired, or torn down)
    the server returns LogStreamError{code: "SESSION_NOT_FOUND"} and
    the client should fall back to a fresh init.
    """
    resume_offset: builtins.int
    """Cumulative byte offset the client has successfully received and
    processed. On resume, the server replays starting from this offset.
    Bytes that were in flight at disconnect (sent by the server but not
    received by the client) are NOT included in resume_offset and will
    be replayed — this gives at-least-once delivery without an explicit
    ack channel.

    Monotonicity is recommended but not required by the server: a
    duplicate or lower resume_offset just replays more bytes than
    strictly necessary. The client is the authoritative source for what
    it has delivered; the server does not track per-client state.

    If resume_offset is below the oldest byte still held in the server's
    replay window, the server emits LogStreamError{code: "REPLAY_GAP"}
    (terminal — see LogStreamError docs). Ignored when resume_session_id
    is empty.
    """
    def __init__(
        self,
        *,
        sandbox_id: builtins.str = ...,
        follow: builtins.bool = ...,
        tail_lines: builtins.int = ...,
        since_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        timestamps: builtins.bool = ...,
        resume_session_id: builtins.str = ...,
        resume_offset: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["since_time", b"since_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["follow", b"follow", "resume_offset", b"resume_offset", "resume_session_id", b"resume_session_id", "sandbox_id", b"sandbox_id", "since_time", b"since_time", "tail_lines", b"tail_lines", "timestamps", b"timestamps"]) -> None: ...

global___LogStreamInit = LogStreamInit

@typing_extensions.final
class LogStreamClose(google.protobuf.message.Message):
    """LogStreamClose signals that the client is closing the log stream.
    In follow mode, this stops tailing new logs.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___LogStreamClose = LogStreamClose

@typing_extensions.final
class LogStreamResponse(google.protobuf.message.Message):
    """LogStreamResponse is sent by server with log data or status updates."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    COMPLETE_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> global___LogStreamData:
        """Log data chunk."""
    @property
    def error(self) -> global___LogStreamError:
        """Error during log streaming.
        This is the final message for a failed stream.
        """
    @property
    def complete(self) -> global___LogStreamComplete:
        """Stream completed indicator (for non-follow mode).
        This is the final message for a successful non-follow stream.
        """
    def __init__(
        self,
        *,
        data: global___LogStreamData | None = ...,
        error: global___LogStreamError | None = ...,
        complete: global___LogStreamComplete | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["complete", b"complete", "data", b"data", "error", b"error", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["complete", b"complete", "data", b"data", "error", b"error", "response", b"response"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["response", b"response"]) -> typing_extensions.Literal["data", "error", "complete"] | None: ...

global___LogStreamResponse = LogStreamResponse

@typing_extensions.final
class LogStreamData(google.protobuf.message.Message):
    """LogStreamData carries a chunk of log data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    """Raw log bytes."""
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp when this log data was generated.
        Only present if timestamps were requested in LogStreamInit.
        """
    session_id: builtins.str
    """Server-issued opaque session identifier. Stable for the lifetime of the
    underlying Runner session and present on every LogStreamData message
    (including resumes). The client SHOULD persist this and pass it as
    LogStreamInit.resume_session_id on a subsequent stream if the original
    is interrupted, to reattach without losing the live tail.
    """
    offset: builtins.int
    """Cumulative byte offset *after* this chunk — i.e., for a 100-byte
    chunk starting at offset 500, this field is 600. The client should
    persist the highest value it has successfully received and echo it
    as LogStreamInit.resume_offset on the next init if the stream is
    interrupted.

    The server does not track per-client delivery state; the client's
    echoed offset is the authoritative ack for resume purposes. The
    server retains a bounded replay window after the chunk is sent (see
    LogStreamInit.resume_offset for REPLAY_GAP semantics).
    """
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        session_id: builtins.str = ...,
        offset: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "offset", b"offset", "session_id", b"session_id", "timestamp", b"timestamp"]) -> None: ...

global___LogStreamData = LogStreamData

@typing_extensions.final
class LogStreamComplete(google.protobuf.message.Message):
    """LogStreamComplete indicates that the log stream has ended.
    This is only sent in non-follow mode after all logs have been delivered.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___LogStreamComplete = LogStreamComplete

@typing_extensions.final
class LogStreamError(google.protobuf.message.Message):
    """LogStreamError indicates an error during log streaming. Every value of
    LogStreamError is terminal: it is the final message on the stream and
    the client MUST NOT attempt to consume additional frames after
    receiving it. The `code` field tells the client what shape its next
    init (if any) should take.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    message: builtins.str
    """Human-readable error message."""
    code: builtins.str
    """Error code for programmatic error handling. Each documented code
    ends with the prescribed client retry shape (no retry / fresh init
    / resume init from head).
    Examples:
      "SANDBOX_NOT_FOUND"        — terminal; no retry.
      "PERMISSION_DENIED"        — terminal; no retry.
      "RUNNER_UNAVAILABLE"       — transient; retry with FRESH init
                                   (resume not possible — logs moved).
      "RUNNER_DRAINING"          — transient; retry with FRESH init
                                   (resume not possible — logs moved).
      "SESSION_NOT_FOUND"        — resume_session_id is unknown or
                                   expired; retry with FRESH init.
      "REPLAY_GAP"               — resume_offset was below the oldest
                                   byte still in the server's replay
                                   window; some bytes were permanently
                                   missed. Terminal; client may
                                   immediately reconnect with FRESH init
                                   (no resume_offset) to resume the live
                                   tail from the current head.
      "INVALID_RESUME_OFFSET"    — resume_offset is ahead of any byte the
                                   server has emitted; terminal, no retry
                                   (the echoed offset is corrupt).
    """
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        code: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "message", b"message"]) -> None: ...

global___LogStreamError = LogStreamError
