# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: cwsandbox-client
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cwsandbox._proto import volume_pb2 as coreweave_dot_sandbox_dot_v1_dot_volume__pb2


class VolumeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVolume = channel.unary_unary(
                '/coreweave.sandbox.v1.VolumeService/CreateVolume',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.CreateVolumeRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.FromString,
                )
        self.GetVolume = channel.unary_unary(
                '/coreweave.sandbox.v1.VolumeService/GetVolume',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.GetVolumeRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.FromString,
                )
        self.ListVolumes = channel.unary_unary(
                '/coreweave.sandbox.v1.VolumeService/ListVolumes',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.ListVolumesRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.ListVolumesResponse.FromString,
                )
        self.UpdateVolume = channel.unary_unary(
                '/coreweave.sandbox.v1.VolumeService/UpdateVolume',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.UpdateVolumeRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.FromString,
                )
        self.DeleteVolume = channel.unary_unary(
                '/coreweave.sandbox.v1.VolumeService/DeleteVolume',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.DeleteVolumeRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.FromString,
                )
        self.ValidateVolume = channel.unary_unary(
                '/coreweave.sandbox.v1.VolumeService/ValidateVolume',
                request_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.ValidateVolumeRequest.SerializeToString,
                response_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.FromString,
                )


class VolumeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateVolume(self, request, context):
        """CreateVolume registers a Volume. Returns immediately in
        VOLUME_STATE_VALIDATING; poll GetVolume for READY/ERROR.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVolumes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVolume(self, request, context):
        """UpdateVolume patches mutable fields. An absent or "*" update_mask is a
        full replace; changing an immutable field (volume_id, spec.source,
        spec.read_only) returns INVALID_ARGUMENT. In effect only
        spec.description is updatable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVolume(self, request, context):
        """DeleteVolume deregisters a Volume. Deletion is asynchronous: the returned
        resource is in VOLUME_STATE_DELETING while platform-created mount
        plumbing is cleaned up, after which GetVolume returns NOT_FOUND. The
        source storage and its data are never touched. Fails FAILED_PRECONDITION
        (CWSANDBOX_VOLUME_IN_USE) while non-terminal sandboxes are attached.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateVolume(self, request, context):
        """ValidateVolume triggers an on-demand re-validation of the volume's
        backing source — the same checks the platform runs periodically.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VolumeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVolume,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.CreateVolumeRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.SerializeToString,
            ),
            'GetVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVolume,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.GetVolumeRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.SerializeToString,
            ),
            'ListVolumes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVolumes,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.ListVolumesRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.ListVolumesResponse.SerializeToString,
            ),
            'UpdateVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVolume,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.UpdateVolumeRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.SerializeToString,
            ),
            'DeleteVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVolume,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.DeleteVolumeRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.SerializeToString,
            ),
            'ValidateVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateVolume,
                    request_deserializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.ValidateVolumeRequest.FromString,
                    response_serializer=coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coreweave.sandbox.v1.VolumeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VolumeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.VolumeService/CreateVolume',
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.CreateVolumeRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.VolumeService/GetVolume',
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.GetVolumeRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListVolumes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.VolumeService/ListVolumes',
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.ListVolumesRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.ListVolumesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.VolumeService/UpdateVolume',
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.UpdateVolumeRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.VolumeService/DeleteVolume',
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.DeleteVolumeRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coreweave.sandbox.v1.VolumeService/ValidateVolume',
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.ValidateVolumeRequest.SerializeToString,
            coreweave_dot_sandbox_dot_v1_dot_volume__pb2.Volume.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
